"""adds attack types

Revision ID: 0156e64f44a5
Revises: d140ae6280ce
Create Date: 2019-04-11 01:11:34.266782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0156e64f44a5'
down_revision = 'd140ae6280ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    attack_types = postgresql.ENUM('low', 'middle', 'high', 'special_middle', 'special_low', name='attacktypes')
    attack_types.create(op.get_bind())
    op.add_column('moves', sa.Column('attack_type', sa.Enum('low', 'middle', 'high', 'special_middle', 'special_low', name='attacktypes'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'attack_type')
    attack_types = postgresql.ENUM('low', 'middle', 'high', 'special_middle', 'special_low', name='attacktypes')
    attack_types.drop(op.get_bind())
    # ### end Alembic commands ###
